# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-23 02:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warhawks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='posted_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
