# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-24 03:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warhawks', '0003_apartmentcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mt', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('file_content', models.FileField(upload_to='')),
                ('downloads', models.IntegerField()),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('study_material_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warhawks.M_type')),
            ],
        ),
    ]
