# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-24 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhawks', '0004_m_type_studymaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymaterial',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
    ]
