# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-26 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhawks', '0006_lfcategory_lostandfound'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostandfound',
            name='hits',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lostandfound',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
