# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-05 02:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhawks', '0009_studymaterial_preview_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostandfound',
            name='found_or_lost_on',
            field=models.DateField(default=datetime.datetime(2018, 6, 5, 8, 39, 31, 482924)),
        ),
    ]
