# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-07 12:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhawks', '0010_lostandfound_found_or_lost_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostandfound',
            name='found_or_lost_on',
            field=models.DateField(default=datetime.datetime(2018, 6, 7, 17, 58, 53, 546910)),
        ),
    ]
