# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-07 13:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhawks', '0012_auto_20180607_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=250)),
                ('full_name', models.CharField(max_length=250)),
                ('feedback', models.TextField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='lostandfound',
            name='found_or_lost_on',
            field=models.DateField(default=datetime.datetime(2018, 6, 7, 18, 59, 38, 23600)),
        ),
    ]
