# Generated by Django 2.2 on 2019-10-26 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhawks', '0015_auto_20180608_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostandfound',
            name='found_or_lost_on',
            field=models.DateField(default=datetime.datetime(2019, 10, 26, 11, 48, 51, 464694)),
        ),
    ]
