# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-07 12:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='n_apartment',
            old_name='job',
            new_name='apartment',
        ),
    ]
